trillian:
  enabled: true
  initContainerImage:
    netcat:
      registry: quay.io
      repository: securesign/netcat
      version: v1.0.0
    curl:
      registry: registry.access.redhat.com
      repository: ubi9/ubi-minimal
      version: latest
      imagePullPolicy: IfNotPresent
  namespace:
    name: trillian-system
    create: false

rekor:
  namespace:
    name: rekor-system
    create: false
  server:
    ingress:
      className: ""
      annotations:
        route.openshift.io/termination: "edge"
      hosts:
        - host: rekor.apps.open-svc-sts.k1wl.p1.openshiftapps.com
          path: /
  redis:
    args:
      - /usr/bin/run-redis
      - --bind
      - 0.0.0.0
      - --appendonly
      - "yes"
    image:
      registry: registry.redhat.io
      repository: rhel9/redis-6
      version: "sha256:031a5a63611e1e6a9fec47492a32347417263b79ad3b63bcee72fc7d02d64c94"
      pullPolicy: IfNotPresent
      version: latest
  initContainerImage:
    curl:
      registry: registry.access.redhat.com
      repository: ubi9/ubi-minimal
      version: "latest"
      imagePullPolicy: IfNotPresent

fulcio:
  namespace:
    name: fulcio-system
    create: false
  createcerts:
    enabled: true
  server:
    secret: fulcio-secret-rh
    ingress:
      http:
        annotations:
          route.openshift.io/termination: "edge"
        className: ""
        hosts:
          - host: fulcio.apps.open-svc-sts.k1wl.p1.openshiftapps.com
            path: /
  config:
    contents:
      OIDCIssuers:
        ? https://rh-oidc.s3.us-east-1.amazonaws.com/21o4ml1f5kchd6ee9nmh5dhc6efqba38
        : IssuerURL: https://rh-oidc.s3.us-east-1.amazonaws.com/21o4ml1f5kchd6ee9nmh5dhc6efqba38
          ClientID: sigstore
          Type: kubernetes
        ? https://keycloak-keycloak.apps.open-svc-sts.k1wl.p1.openshiftapps.com/auth/realms/sigstore
        : IssuerURL: https://keycloak-keycloak.apps.open-svc-sts.k1wl.p1.openshiftapps.com/auth/realms/sigstore
          ClientID: sigstore
          Type: email

tuf:
  deployment:
    registry: quay.io
    repository: ablock/tuf-server
    version: "sha256:c4f534807b331e97b107d908b7e0cf14a896399bc372bca6a2c7e4f6d730807c"
  namespace:
    name: tuf-system
    create: false
  secrets:
    fulcio:
      name: fulcio-secret-rh
  enabled: true
  ingress:
    className: ""
    annotations:
      route.openshift.io/termination: "edge"
    http:
      hosts:
        - host: tuf.apps.open-svc-sts.k1wl.p1.openshiftapps.com
          path: /

ctlog:
  namespace:
    name: ctlog-system
    create: false
  enabled: true
  createctconfig:
    logPrefix: scaffolding
    backoffLimit: 30

copySecretJob:
  enabled: true
  backoffLimit: 1000
